"""
联合通信/计算资源分配，对应方程（17）和（27）。
此处固定由 :mod:dm_jcr.offloading 生成的任务到节点的映射。对于每个已映射的任务，一种策略会分配三种连续资源：
带宽 b；
边缘CPU频率 f；
边缘节点发射功率 p。

论文采用了比例归一化（方程（27）），使得每个节点上的分配都满足问题（17）中的总带宽、CPU和功率约束。该模块实现了该投影，并利用代码库中已有的信道和任务模型，对由此产生的直传任务进行评估。
中继分配有意留待下一增量处理：中继任务需要在两个节点（中继无人机和执行节点）上占用资源，而直传任务仅在其所选执行节点上消耗资源。
"""

from __future__ import annotations

from dataclasses import dataclass
from math import isclose, isfinite
from typing import Iterable, Mapping

import numpy as np

from dm_jcr.channel import achievable_rate_bps
from dm_jcr.task_model import (
    DEFAULT_CPU_ENERGY_COEFFICIENT,
    ComputationTask,
    DirectLinkResources,
    DirectTaskEvaluation,
    evaluate_direct_task,
)

_EPSILON = 1.0e-12


def _finite_non_negative(name: str, value: float) -> float:
    value = float(value)
    if not isfinite(value) or value < 0.0:
        raise ValueError(f"{name} must be finite and non-negative")
    return value


def _finite_positive(name: str, value: float) -> float:
    value = float(value)
    if not isfinite(value) or value <= 0.0:
        raise ValueError(f"{name} must be finite and greater than 0")
    return value


def _clean_identifier(name: str, value: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{name} must be a non-empty string")
    return value.strip()


@dataclass(frozen=True)
class NodeResourceCapacity:
    """Total allocable resources of one UAV or RSU in a time slot."""

    node_id: str
    total_bandwidth_hz: float
    total_cpu_frequency_hz: float
    total_transmit_power_w: float

    def __post_init__(self) -> None:
        object.__setattr__(self, "node_id", _clean_identifier("node_id", self.node_id))
        object.__setattr__(
            self,
            "total_bandwidth_hz",
            _finite_positive("total_bandwidth_hz", self.total_bandwidth_hz),
        )
        object.__setattr__(
            self,
            "total_cpu_frequency_hz",
            _finite_positive(
                "total_cpu_frequency_hz", self.total_cpu_frequency_hz
            ),
        )
        object.__setattr__(
            self,
            "total_transmit_power_w",
            _finite_positive(
                "total_transmit_power_w", self.total_transmit_power_w
            ),
        )


@dataclass(frozen=True)
class DirectTaskContext:
    """Fixed environment and mapping information for one direct task.

    ``node_id`` is the output of equations (10)-(11).  The vehicle transmit
    power and the channel states are environmental inputs; bandwidth, edge CPU
    frequency and edge-node transmit power are generated by the allocation
    strategy.
    """

    task_id: str
    node_id: str
    task: ComputationTask
    uplink_channel_gain: float
    downlink_channel_gain: float
    vehicle_transmit_power_w: float
    noise_psd_w_hz: float
    uplink_interference_power_w: float = 0.0
    downlink_interference_power_w: float = 0.0

    def __post_init__(self) -> None:
        object.__setattr__(self, "task_id", _clean_identifier("task_id", self.task_id))
        object.__setattr__(self, "node_id", _clean_identifier("node_id", self.node_id))
        if not isinstance(self.task, ComputationTask):
            raise TypeError("task must be a ComputationTask")
        for name in (
            "uplink_channel_gain",
            "downlink_channel_gain",
            "vehicle_transmit_power_w",
            "uplink_interference_power_w",
            "downlink_interference_power_w",
        ):
            object.__setattr__(
                self, name, _finite_non_negative(name, getattr(self, name))
            )
        object.__setattr__(
            self,
            "noise_psd_w_hz",
            _finite_positive("noise_psd_w_hz", self.noise_psd_w_hz),
        )
        if self.uplink_channel_gain == 0.0:
            raise ValueError("uplink_channel_gain must be greater than 0")
        if self.downlink_channel_gain == 0.0:
            raise ValueError("downlink_channel_gain must be greater than 0")


@dataclass(frozen=True)
class RawTaskAllocation:
    """Unconstrained positive scores emitted by an optimizer or generator."""

    task_id: str
    node_id: str
    bandwidth_score: float
    cpu_score: float
    power_score: float

    def __post_init__(self) -> None:
        object.__setattr__(self, "task_id", _clean_identifier("task_id", self.task_id))
        object.__setattr__(self, "node_id", _clean_identifier("node_id", self.node_id))
        for name in ("bandwidth_score", "cpu_score", "power_score"):
            object.__setattr__(
                self, name, _finite_non_negative(name, getattr(self, name))
            )


@dataclass(frozen=True)
class FeasibleTaskAllocation:
    """Projected resource allocation satisfying per-node totals."""

    task_id: str
    node_id: str
    bandwidth_hz: float
    cpu_frequency_hz: float
    node_transmit_power_w: float

    def __post_init__(self) -> None:
        object.__setattr__(self, "task_id", _clean_identifier("task_id", self.task_id))
        object.__setattr__(self, "node_id", _clean_identifier("node_id", self.node_id))
        object.__setattr__(
            self,
            "bandwidth_hz",
            _finite_positive("bandwidth_hz", self.bandwidth_hz),
        )
        object.__setattr__(
            self,
            "cpu_frequency_hz",
            _finite_positive("cpu_frequency_hz", self.cpu_frequency_hz),
        )
        object.__setattr__(
            self,
            "node_transmit_power_w",
            _finite_non_negative(
                "node_transmit_power_w", self.node_transmit_power_w
            ),
        )


@dataclass(frozen=True)
class ObjectiveWeights:
    """Weights ``rho`` and ``xi`` in equation (17)."""

    latency: float = 0.5
    energy: float = 0.5

    def __post_init__(self) -> None:
        latency = _finite_non_negative("latency", self.latency)
        energy = _finite_non_negative("energy", self.energy)
        if not isclose(latency + energy, 1.0, rel_tol=0.0, abs_tol=1.0e-9):
            raise ValueError("latency and energy weights must sum to 1")
        object.__setattr__(self, "latency", latency)
        object.__setattr__(self, "energy", energy)


@dataclass(frozen=True)
class ObjectiveNormalization:
    """Explicit normalization constants for the weighted objective.

    The paper states that latency and energy are normalized but does not give
    the exact normalization formula.  This implementation uses each task's
    deadline as its latency reference by default, and a caller-supplied energy
    reference.  A common latency reference can be supplied when reproducing a
    dataset-level normalization protocol.
    """

    energy_reference_j: float
    latency_reference_s: float | None = None

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "energy_reference_j",
            _finite_positive("energy_reference_j", self.energy_reference_j),
        )
        if self.latency_reference_s is not None:
            object.__setattr__(
                self,
                "latency_reference_s",
                _finite_positive(
                    "latency_reference_s", self.latency_reference_s
                ),
            )


@dataclass(frozen=True)
class TaskAllocationEvaluation:
    """Evaluation of one task after projection."""

    task_id: str
    node_id: str
    allocation: FeasibleTaskAllocation
    uplink_rate_bps: float
    downlink_rate_bps: float
    metrics: DirectTaskEvaluation
    normalized_latency: float
    normalized_energy: float


@dataclass(frozen=True)
class JointAllocationEvaluation:
    """Equation (17) objective and feasibility report for one time slot."""

    tasks: tuple[TaskAllocationEvaluation, ...]
    mean_normalized_latency: float
    mean_normalized_energy: float
    weighted_objective: float
    resource_constraints_satisfied: bool
    deadline_constraints_satisfied: bool

    @property
    def feasible(self) -> bool:
        return (
            self.resource_constraints_satisfied
            and self.deadline_constraints_satisfied
        )


def proportional_normalize(
    scores: Iterable[float],
    total_resource: float,
) -> np.ndarray:
    """Apply the proportional normalization in equation (27).

    For a non-zero score vector ``gamma`` this returns
    ``total_resource / sum(gamma) * gamma``.  A zero vector contains no ratio
    information, so the only symmetric deterministic fallback is an equal
    split.  Negative, infinite and empty inputs are rejected.
    """

    total = _finite_positive("total_resource", total_resource)
    vector = np.asarray(tuple(scores), dtype=np.float64)
    if vector.ndim != 1 or vector.size == 0:
        raise ValueError("scores must be a non-empty one-dimensional sequence")
    if not np.all(np.isfinite(vector)) or np.any(vector < 0.0):
        raise ValueError("scores must contain finite, non-negative values")

    score_sum = float(vector.sum())
    if score_sum <= _EPSILON:
        return np.full(vector.shape, total / vector.size, dtype=np.float64)
    return vector * (total / score_sum)


def _index_capacities(
    capacities: Iterable[NodeResourceCapacity],
) -> dict[str, NodeResourceCapacity]:
    indexed: dict[str, NodeResourceCapacity] = {}
    for capacity in capacities:
        if capacity.node_id in indexed:
            raise ValueError(f"duplicate capacity for node {capacity.node_id!r}")
        indexed[capacity.node_id] = capacity
    if not indexed:
        raise ValueError("at least one node capacity is required")
    return indexed


def project_resource_strategy(
    raw_allocations: Iterable[RawTaskAllocation],
    capacities: Iterable[NodeResourceCapacity],
) -> tuple[FeasibleTaskAllocation, ...]:
    """Project a raw strategy onto all resource constraints in equation (17).

    Projection is performed independently for bandwidth, CPU and power, and
    independently for each node.  Relative scores are preserved exactly as in
    equation (27).
    """

    raw = tuple(raw_allocations)
    if not raw:
        raise ValueError("at least one raw allocation is required")
    capacity_by_node = _index_capacities(capacities)

    task_ids = [item.task_id for item in raw]
    if len(set(task_ids)) != len(task_ids):
        raise ValueError("task_id values must be unique")

    result: list[FeasibleTaskAllocation | None] = [None] * len(raw)
    indices_by_node: dict[str, list[int]] = {}
    for index, item in enumerate(raw):
        if item.node_id not in capacity_by_node:
            raise ValueError(f"missing capacity for node {item.node_id!r}")
        indices_by_node.setdefault(item.node_id, []).append(index)

    for node_id, indices in indices_by_node.items():
        capacity = capacity_by_node[node_id]
        bandwidth = proportional_normalize(
            (raw[i].bandwidth_score for i in indices),
            capacity.total_bandwidth_hz,
        )
        cpu = proportional_normalize(
            (raw[i].cpu_score for i in indices),
            capacity.total_cpu_frequency_hz,
        )
        power = proportional_normalize(
            (raw[i].power_score for i in indices),
            capacity.total_transmit_power_w,
        )

        for local_index, raw_index in enumerate(indices):
            item = raw[raw_index]
            result[raw_index] = FeasibleTaskAllocation(
                task_id=item.task_id,
                node_id=item.node_id,
                bandwidth_hz=float(bandwidth[local_index]),
                cpu_frequency_hz=float(cpu[local_index]),
                node_transmit_power_w=float(power[local_index]),
            )

    return tuple(item for item in result if item is not None)


def verify_resource_constraints(
    allocations: Iterable[FeasibleTaskAllocation],
    capacities: Iterable[NodeResourceCapacity],
    *,
    tolerance: float = 1.0e-8,
) -> bool:
    """Return whether all three per-node totals satisfy equation (17)."""

    tolerance = _finite_non_negative("tolerance", tolerance)
    capacity_by_node = _index_capacities(capacities)
    totals = {
        node_id: np.zeros(3, dtype=np.float64) for node_id in capacity_by_node
    }
    for item in allocations:
        if item.node_id not in capacity_by_node:
            return False
        totals[item.node_id] += np.array(
            [
                item.bandwidth_hz,
                item.cpu_frequency_hz,
                item.node_transmit_power_w,
            ],
            dtype=np.float64,
        )

    for node_id, values in totals.items():
        capacity = capacity_by_node[node_id]
        limits = np.array(
            [
                capacity.total_bandwidth_hz,
                capacity.total_cpu_frequency_hz,
                capacity.total_transmit_power_w,
            ],
            dtype=np.float64,
        )
        if np.any(values < -tolerance) or np.any(values - limits > tolerance):
            return False
    return True


def evaluate_direct_resource_strategy(
    contexts: Iterable[DirectTaskContext],
    allocations: Iterable[FeasibleTaskAllocation],
    capacities: Iterable[NodeResourceCapacity],
    normalization: ObjectiveNormalization,
    weights: ObjectiveWeights = ObjectiveWeights(),
    *,
    energy_coefficient: float = DEFAULT_CPU_ENERGY_COEFFICIENT,
) -> JointAllocationEvaluation:
    """Evaluate a projected direct-link strategy under equation (17).

    The function computes rates with equation (8), task latency/energy with
    equations (12)-(13), normalized metrics, and the weighted objective ``J``.
    It does not hide infeasibility with a penalty: resource and deadline
    constraints are reported separately, matching the constrained formulation.
    """

    context_items = tuple(contexts)
    allocation_items = tuple(allocations)
    if not context_items:
        raise ValueError("at least one task context is required")

    context_by_task = {item.task_id: item for item in context_items}
    allocation_by_task = {item.task_id: item for item in allocation_items}
    if len(context_by_task) != len(context_items):
        raise ValueError("context task_id values must be unique")
    if len(allocation_by_task) != len(allocation_items):
        raise ValueError("allocation task_id values must be unique")
    if context_by_task.keys() != allocation_by_task.keys():
        raise ValueError("contexts and allocations must contain the same tasks")

    task_results: list[TaskAllocationEvaluation] = []
    for context in context_items:
        allocation = allocation_by_task[context.task_id]
        if allocation.node_id != context.node_id:
            raise ValueError(
                f"task {context.task_id!r} is mapped to {context.node_id!r}, "
                f"not {allocation.node_id!r}"
            )
        if allocation.bandwidth_hz <= 0.0:
            raise ValueError("projected bandwidth must be greater than 0")
        if allocation.cpu_frequency_hz <= 0.0:
            raise ValueError("projected CPU frequency must be greater than 0")
        if allocation.node_transmit_power_w < 0.0:
            raise ValueError("projected node transmit power cannot be negative")

        uplink_rate = achievable_rate_bps(
            bandwidth_hz=allocation.bandwidth_hz,
            transmit_power_w=context.vehicle_transmit_power_w,
            channel_gain=context.uplink_channel_gain,
            noise_psd_w_hz=context.noise_psd_w_hz,
            interference_power_w=context.uplink_interference_power_w,
        )
        downlink_rate = achievable_rate_bps(
            bandwidth_hz=allocation.bandwidth_hz,
            transmit_power_w=allocation.node_transmit_power_w,
            channel_gain=context.downlink_channel_gain,
            noise_psd_w_hz=context.noise_psd_w_hz,
            interference_power_w=context.downlink_interference_power_w,
        )
        if uplink_rate <= 0.0 or downlink_rate <= 0.0:
            raise ValueError("allocated resources produce a zero communication rate")

        metrics = evaluate_direct_task(
            task=context.task,
            resources=DirectLinkResources(
                uplink_rate_bps=uplink_rate,
                downlink_rate_bps=downlink_rate,
                cpu_frequency_hz=allocation.cpu_frequency_hz,
                vehicle_tx_power_w=context.vehicle_transmit_power_w,
                node_tx_power_w=allocation.node_transmit_power_w,
            ),
            energy_coefficient=energy_coefficient,
        )
        latency_reference = (
            normalization.latency_reference_s
            if normalization.latency_reference_s is not None
            else context.task.max_latency_s
        )
        task_results.append(
            TaskAllocationEvaluation(
                task_id=context.task_id,
                node_id=context.node_id,
                allocation=allocation,
                uplink_rate_bps=float(uplink_rate),
                downlink_rate_bps=float(downlink_rate),
                metrics=metrics,
                normalized_latency=float(
                    metrics.total_latency_s / latency_reference
                ),
                normalized_energy=float(
                    metrics.total_energy_j / normalization.energy_reference_j
                ),
            )
        )

    mean_latency = float(
        np.mean([item.normalized_latency for item in task_results])
    )
    mean_energy = float(
        np.mean([item.normalized_energy for item in task_results])
    )
    objective = weights.latency * mean_latency + weights.energy * mean_energy

    return JointAllocationEvaluation(
        tasks=tuple(task_results),
        mean_normalized_latency=mean_latency,
        mean_normalized_energy=mean_energy,
        weighted_objective=float(objective),
        resource_constraints_satisfied=verify_resource_constraints(
            allocation_items, capacities
        ),
        deadline_constraints_satisfied=all(
            item.metrics.meets_deadline for item in task_results
        ),
    )


def allocations_by_task(
    allocations: Iterable[FeasibleTaskAllocation],
) -> Mapping[str, FeasibleTaskAllocation]:
    """Build a read-only-style task lookup and reject duplicate task IDs."""

    result: dict[str, FeasibleTaskAllocation] = {}
    for allocation in allocations:
        if allocation.task_id in result:
            raise ValueError(f"duplicate task_id {allocation.task_id!r}")
        result[allocation.task_id] = allocation
    return result


__all__ = [
    "DirectTaskContext",
    "FeasibleTaskAllocation",
    "JointAllocationEvaluation",
    "NodeResourceCapacity",
    "ObjectiveNormalization",
    "ObjectiveWeights",
    "RawTaskAllocation",
    "TaskAllocationEvaluation",
    "allocations_by_task",
    "evaluate_direct_resource_strategy",
    "project_resource_strategy",
    "proportional_normalize",
    "verify_resource_constraints",
]
